### ISSUE TITLE
vue-swipe-tab not working in standard vue-cli vue-webpack template environment

### ISSUE THREAD

**Issue by franktopel** [zhangxiang958/vue-tab#1]
Please fix your code example in README.MD because it does not work. I currently fail to use your component.

You advise to `import Tab from 'vue-swipe-tab';` but you are actually using a custom element `<tabs>` in your template. Please show working code.

In your _demo code_ you are instead using 

`import { Tabs, Tab }  from './Tab';`

and then in the components property:

`components: { Tabs, Tab }`

both of which are commented out in your demo code (**why?**).

-----

**This is how I tried to make it work**:

`import { Tabs, Tab } from 'vue-swipe-tab';`

`components: { Tabs, Tab }` 

`methods: { 
            tabChange(idx) {
                console.log(idx);
            }
`

```
<Tabs @changePage="tabChange" indexTab="friend">
                            <TabPanel
                                label="好友榜"
                                hash="friend"
                                fontsize="36"
                                tabheight="90"
                                color="red">
                                <div class="first">1</div>
                            </TabPanel>
                            <TabPanel
                                label="全省榜"
                                hash="convince"
                                fontsize="36"
                                tabheight="90"
                                color="red">
                                <div class="second">2</div>
                            </TabPanel>
                            <TabPanel
                                label="全国榜"
                                hash="country"
                                fontsize="36"
                                tabheight="90"
                                color="red">
                                <div class="three">3</div>
                            </TabPanel>
                        </Tabs>
```

but that just gives me

`[Vue warn]: Unknown custom element: <Tabs> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

and

`[Vue warn]: Unknown custom element: <TabPanel> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

---

2nd try:

`import Tabs from 'vue-swipe-tab';
import Tab from 'vue-swipe-tab';`

and then 

```
<Tabs @changePage="tabChange" indexTab="friend">
                            <Tab
                                label="好友榜"
                                hash="friend"
                                fontsize="36"
                                tabheight="90"
                                color="red">
                                <div class="first">1</div>
                            </Tab>
                            <Tab
                                label="全省榜"
                                hash="convince"
                                fontsize="36"
                                tabheight="90"
                                color="red">
                                <div class="second">2</div>
                            </Tab>
                            <Tab
                                label="全国榜"
                                hash="country"
                                fontsize="36"
                                tabheight="90"
                                color="red">
                                <div class="three">3</div>
                            </Tab>
                        </Tabs>
``` 

gives me 

`[Vue warn]: Failed to mount component: template or render function not defined.`

twice in the console.

**Comment by zhangxiang958** [comment]
@franktopel which version you are using? please use the version at 2.0.2.
vue-swipe-tab is a vue plugin, so you don't need to register components' name in the component options.
so you just need to use it like this in app.js(app entry):
```
import Tab from 'vue-swipe-tab';
Vue.use(Tab);
```
and then, you can write it everywhere in your vue component without register it in component options: 
```
<script>
    export default {
        created(){
        },
        mounted(){
        },
        data(){
            return {
            }
        },
    }
</script>

<template>
    <div class="app">
        <Tabs indexTab="convince">
            <TabPanel label="好友榜" hash="friend" fontsize="36" tabheight="90" color="red">
                <div class="first"></div>
            </TabPanel>
            <TabPanel label="全省榜" hash="convince" fontsize="36" tabheight="90" color="red">
                <div class="second"></div>
            </TabPanel>
            <TabPanel label="全国榜" hash="country" fontsize="36" tabheight="90" color="red">
                <div class="three"></div>
            </TabPanel>
        </Tabs>
    </div>
</template>
```

**Comment by franktopel** [comment]
I am using version 2.0.2 along with vue 2 and vue-router. I added the code you suggested to my `main.js` and removed the import and the component declaration in my vue component.

That gives me

```
[Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <Tabs>
       <DetailBase> at src/components/sections/detail/DetailBase.vue
         <PageTemplate> at src/components/templates/PageBase.vue
           <Detail> at src/components/templates/Detail.vue
             <App> at src/App.vue
               <Root>
```

twice.

**Comment by zhangxiang958** [comment]
@franktopel can you show me the code that using vue-swipe-tab?
this problem seem like cause by vue or webpack, are you using webpack to build you project and import vue.js by using <script> ?

**Comment by zhangxiang958** [comment]
@franktopel  in vue issuse https://github.com/vuejs/vue-router/issues/713

**Comment by franktopel** [comment]
I am using [vue-webpack template](https://github.com/vuejs-templates/webpack). This is already a very big Vue application and my current task is to add a swipeable tab to one of the views.

This is my main.js (webpack entry point):

```
import Vue from 'vue';
import App from './App';

import { sync } from 'vuex-router-sync';
import i18n from './utils/i18n';
import { router } from './router';
import store from './store';
import Tab from 'vue-swipe-tab';

Vue.use(Tab);

sync(store, router);

import './setup';
import './plugins';

// global components
import './components/common';
import './components/modules';
import './components/templates';

import * as filters from './utils/filters';
import * as directives from './utils/directives';

// register global filters
Object.keys(filters).forEach(key => {
    Vue.filter(key, filters[key]);
});

// register global directives
Object.keys(directives).forEach(key => {
    Vue.directive(key, directives[key]);
});

// disable production tip in dev tools
Vue.config.productionTip = false;

new Vue({
    components: { App },

    el: '#app',

    router,
    store,
    i18n,

    template: '<App/>',

    created() {
        this.$i18n.locale = this.$store.getters['language/current'] || 'de';

        this.$store.dispatch('initApp');
    }
});
```

This is the relevant part of the webpack config:

```
resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
      'vue$': 'vue/dist/vue.esm.js',
      ...
    }
}
```

**Comment by zhangxiang958** [comment]
@franktopel edit webpack config seem can solve this problem: like this
```
module.exports = {
  // ... other options
  resolve: {
    extensions: ['.js', '.vue'],
    alias: {
      'vue$': 'vue/dist/vue.common.js'
    }
  },
  // ... other options
}
```

**Comment by zhangxiang958** [comment]
@franktopel  maybe https://stackoverflow.com/questions/39890005/vue-js-migration-to-2-0-failed-to-mount-component-template-or-render-function can help you to fixed the bug

**Comment by franktopel** [comment]
I tried that, did not change the outcome though. Also, vue.common.js should be for CommonJS imports, not for ES6 imports. The vue documentation says

`'vue$': 'vue/dist/vue.esm.js' // 'vue/dist/vue.common.js' for webpack 1`

**Comment by zhangxiang958** [comment]
@franktopel try vue.esm.js?

**Comment by franktopel** [comment]
vue.esm.js was what was set before I started investigating. Neither vue.esm.js nor vue.common.js change anything about the problem.

As I showed:

```
resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
      'vue$': 'vue/dist/vue.esm.js',
      ...
    }
}
```

This should be correct.

**Comment by zhangxiang958** [comment]
@franktopel can you console the plugin information?
```
import Tab from 'vue-swipe-tab';
console.log(Tab);
```

**Comment by franktopel** [comment]
![image](https://user-images.githubusercontent.com/10668603/31714763-909b46bc-b401-11e7-8ed9-3a71503aff90.png)

Is that what you'd expect to see? Chrome console output.

**Comment by zhangxiang958** [comment]
@franktopel import this plugin success, show me the way you use this plugin: is it like that ?
```
 <Tabs indexTab="convince">
            <TabPanel label="好友榜" hash="friend" fontsize="36" tabheight="90" color="red">
                <div class="first"></div>
            </TabPanel>
            <TabPanel label="全省榜" hash="convince" fontsize="36" tabheight="90" color="red">
                <div class="second"></div>
            </TabPanel>
            <TabPanel label="全国榜" hash="country" fontsize="36" tabheight="90" color="red">
                <div class="three"></div>
            </TabPanel>
        </Tabs>
```

**Comment by franktopel** [comment]
```
<Tabs @changePage="tabChange" indexTab="friend">
  <TabPanel
    label="好友榜"
    hash="friend"
    fontsize="36"
    tabheight="90"
    color="red">
    <div class="first">1</div>
  </TabPanel>
  <TabPanel
    label="全省榜"
    hash="convince"
    fontsize="36"
    tabheight="90"
    color="red">
    <div class="second">2</div>
  </TabPanel>
  <TabPanel
    label="全国榜"
    hash="country"
    fontsize="36"
    tabheight="90"
    color="red">
    <div class="three">3</div>
  </TabPanel>
</Tabs>
```

**Comment by zhangxiang958** [comment]
@franktopel I cannot reappear this problem in my code。please show me your demo on https://jsfiddle.net/chrisvfritz/50wL7mdz/

**Comment by franktopel** [comment]
Can I use import syntax there?

Why don't you share the source code for your working demo in the repo?

**Comment by franktopel** [comment]
Have you ever tested your plugin in the standard vue-webpack template environment?

https://github.com/vuejs-templates/webpack

**Comment by franktopel** [comment]
I just set up a fresh project using the vue-webpack template and followed your instructions.

```
[Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <Tabs>
       <App> at src/App.vue
         <Root>
```

It seems your plugin does not work in the vue standard environment.

I'm going to set up a repo so you can test by yourself: https://github.com/franktopel/vue-swipe-tab-test

**Comment by franktopel** [comment]
The repository is now set up and the latest commit includes your implementation instructions.

**Comment by franktopel** [comment]
As soon as I try to `import Tab from 'vue-swipe-tab'` in main.js I get the following compile error:

```
These dependencies were not found:

* !!vue-style-loader!css-loader?{"minimize":false,"sourceMap":false}!../../vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-caa79648","scoped":true,"hasInlineConfig":false}!sass-loader?{"sourceMap":false}!../../vue-loader/lib/selector?type=styles&index=0&bustCache!./index.vue in ./node_modules/vue-swipe-tab/lib/index.vue
* !!vue-style-loader!css-loader?{"minimize":false,"sourceMap":false}!../../vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-5b59a69f","scoped":true,"hasInlineConfig":false}!sass-loader?{"sourceMap":false}!../../vue-loader/lib/selector?type=styles&index=0&bustCache!./tab.vue in ./node_modules/vue-swipe-tab/lib/tab.vue
```
and the console shows 

`ERROR in ./node_modules/vue-swipe-tab/lib/index.vue Module not found: Error: Can't resolve 'sass-loader' in '/Volumes/Data/Sites/vue-swipe-tab-test/node_modules/vue-swipe-tab/lib' @ ./node_modules/vue-swipe-tab/lib/index.vue 4:2-315 @ ./node_modules/vue-swipe-tab/index.js @ ./src/main.js @ multi ./build/dev-client ./src/main.js`

**Comment by franktopel** [comment]
Is your package.json lacking dependencies? I'm using the latest npm 5.5.1 along with node 6.11.1.

**Comment by franktopel** [comment]
Now I manually installed `sass-loader` and `node-sass` packages which makes the compile error go away. Now we're back to

![image](https://user-images.githubusercontent.com/10668603/31717595-e66b4d70-b40c-11e7-8f25-064aa9bc4792.png)

**Comment by franktopel** [comment]
Just checked. The package.json in `./node_modules/vue-swipe-tab` does not contain _any_ dependencies whatsoever:

```
{
  "_args": [
    [
      {
        "raw": "vue-swipe-tab@^2.0.2",
        "scope": null,
        "escapedName": "vue-swipe-tab",
        "name": "vue-swipe-tab",
        "rawSpec": "^2.0.2",
        "spec": ">=2.0.2 <3.0.0",
        "type": "range"
      },
      "/Volumes/Data/Sites/vue-swipe-tab-test"
    ]
  ],
  "_from": "vue-swipe-tab@>=2.0.2 <3.0.0",
  "_id": "vue-swipe-tab@2.0.2",
  "_inCache": true,
  "_location": "/vue-swipe-tab",
  "_nodeVersion": "6.10.2",
  "_npmOperationalInternal": {
    "host": "s3://npm-registry-packages",
    "tmp": "tmp/vue-swipe-tab-2.0.2.tgz_1504780123950_0.8720360777806491"
  },
  "_npmUser": {
    "name": "shawncheung",
    "email": "958033967@qq.com"
  },
  "_npmVersion": "3.10.10",
  "_phantomChildren": {},
  "_requested": {
    "raw": "vue-swipe-tab@^2.0.2",
    "scope": null,
    "escapedName": "vue-swipe-tab",
    "name": "vue-swipe-tab",
    "rawSpec": "^2.0.2",
    "spec": ">=2.0.2 <3.0.0",
    "type": "range"
  },
  "_requiredBy": [
    "/"
  ],
  "_resolved": "https://registry.npmjs.org/vue-swipe-tab/-/vue-swipe-tab-2.0.2.tgz",
  "_shasum": "1591db336ffc02e82e6ee60e719c973c99eddbce",
  "_shrinkwrap": null,
  "_spec": "vue-swipe-tab@^2.0.2",
  "_where": "/Volumes/Data/Sites/vue-swipe-tab-test",
  "author": {
    "name": "zhangxiang"
  },
  "bugs": {
    "url": "https://github.com/zhangxiang958/vue-tab/issues"
  },
  "dependencies": {},
  "description": "a touch swipe tab component for vue.js(vue2).",
  "devDependencies": {},
  "directories": {},
  "dist": {
    "shasum": "1591db336ffc02e82e6ee60e719c973c99eddbce",
    "tarball": "https://registry.npmjs.org/vue-swipe-tab/-/vue-swipe-tab-2.0.2.tgz"
  },
  "homepage": "https://github.com/zhangxiang958/vue-tab#readme",
  "keywords": [
    "vue",
    "vue-tab",
    "swipe",
    "vue-swipe-tab"
  ],
  "license": "ISC",
  "main": "index.js",
  "maintainers": [
    {
      "name": "shawncheung",
      "email": "958033967@qq.com"
    }
  ],
  "name": "vue-swipe-tab",
  "optionalDependencies": {},
  "readme": "ERROR: No README data found!",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/zhangxiang958/vue-tab.git"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "version": "2.0.2"
}
```

**Comment by franktopel** [comment]
Is your live demo still based on the current version of your code?

**Comment by franktopel** [comment]
I have sent you an invite to collaborate on https://github.com/franktopel/vue-swipe-tab-test

**Comment by franktopel** [comment]
Are you still on this?

**Comment by zhangxiang958** [comment]
@franktopel  I clone https://github.com/franktopel/vue-swipe-tab-test and test my plugin(vue-swipe-tab), 
it occurred a Error: Failed to mount component: template or render function not defined.
but it is not caused by my plugin, it seem like a problem in vue-loader. I test my plugin in this way:
```
<template>
  <div id="app">
    <img src="./assets/logo.png">
    <!-- <router-view/> -->
    <Tabs indexTab="friend">
      <TabPanel
        label="好友榜"
        hash="friend"
        fontsize="36"
        tabheight="90"
        color="red">
        <div class="first">1</div>
      </TabPanel>
      <TabPanel
        label="全省榜"
        hash="convince"
        fontsize="36"
        tabheight="90"
        color="red">
        <div class="second">2</div>
      </TabPanel>
      <TabPanel
        label="全国榜"
        hash="country"
        fontsize="36"
        tabheight="90"
        color="red">
        <div class="three">3</div>
      </TabPanel>
    </Tabs>
  </div>
</template>

<script>
import Tabs from 'vue-swipe-tab/lib/index.vue';
import TabPanel from 'vue-swipe-tab/lib/tab.vue';
export default {
  components: {
    Tabs, TabPanel,
  }
}
</script>
```
it work! But when I use Vue.use() API to register the two component, the Error occurred again:
```
import Tab from 'vue-swipe-tab'
Vue.use(Tab)
``` 
I spend all day to find vue-loader' bug, but still not solve this error, Many people had same problem in Vue2, vue-loader, webpack.
maybe you can find the answers in Vue-loader's issues. https://stackoverflow.com/questions/41983767/vue-template-or-render-function-not-defined-yet-i-am-using-neither

**Comment by franktopel** [comment]
Thanks alot for your effort, I appreciate it! Yet I do not agree that you are closing this issue because it is still not resolved. The link you gave does not address this problem as far as I understand.

**Comment by franktopel** [comment]
I suggest you commit a working implementation in the repository I created and link to that in your README.MD.

**Comment by xkmy** [comment]
<template>
	<div class="app">
		<Tabs indexTab="friend">
			<TabPanel label="好友榜" hash="friend" fontsize="36" tabheight="90" color="red">
				<div class="first">444</div>
			</TabPanel>
			<TabPanel label="全省榜" hash="convince" fontsize="36" tabheight="90" color="red">
				<div class="second">333</div>
			</TabPanel>
			<TabPanel label="全国榜" hash="country" fontsize="36" tabheight="90" color="red">
				<div class="three">222</div>
			</TabPanel>
		</Tabs>
	</div>
</template>
<script>
	import Tabs from 'vue-swipe-tab/lib/index.vue';
	import TabPanel from 'vue-swipe-tab/lib/tab.vue';
	export default {
		components: {
			Tabs,
			TabPanel,
		}
	}
</script>
<style>

</style>

**Comment by xkmy** [comment]
<template>
	<div class="app">
		<Tabs indexTab="friend">
			<TabPanel label="好友榜" hash="friend" fontsize="36" tabheight="90" color="red">
				<div class="first">444</div>
			</TabPanel>
			<TabPanel label="全省榜" hash="convince" fontsize="36" tabheight="90" color="red">
				<div class="second">333</div>
			</TabPanel>
			<TabPanel label="全国榜" hash="country" fontsize="36" tabheight="90" color="red">
				<div class="three">222</div>
			</TabPanel>
		</Tabs>
	</div>
</template>
<script>
	import Tabs from 'vue-swipe-tab/lib/index.vue';
	import TabPanel from 'vue-swipe-tab/lib/tab.vue';
	export default {
		components: {
			Tabs,
			TabPanel,
		}
	}
</script>
<style>

</style>

**Comment by xkmy** [comment]
<template>
	<div class="app">
		<Tabs indexTab="friend">
			<TabPanel label="好友榜" hash="friend" fontsize="36" tabheight="90" color="red">
				<div class="first">444</div>
			</TabPanel>
			<TabPanel label="全省榜" hash="convince" fontsize="36" tabheight="90" color="red">
				<div class="second">333</div>
			</TabPanel>
			<TabPanel label="全国榜" hash="country" fontsize="36" tabheight="90" color="red">
				<div class="three">222</div>
			</TabPanel>
		</Tabs>
	</div>
</template>
<script>
	import Tabs from 'vue-swipe-tab/lib/index.vue';
	import TabPanel from 'vue-swipe-tab/lib/tab.vue';
	export default {
		components: {
			Tabs,
			TabPanel,
		}
	}
</script>
